version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sua-maeEuOdeioReact2x"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
      MSSQL_DATABASE: "master"
    ports:
      - "1433:1433"
  postgresql:
    image: postgres:latest
    container_name: my_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua-maeEuOdeioReact2x
      POSTGRES_DB: sua-mae
    ports:
      - "2345:5432"
   